version: '3'

services:
  postgres:
    container_name: staging
    build:
      context: ../../
      dockerfile: ./docker/staging/Dockerfile
    env_file:
      - ../../.env.example
    hostname: staging
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "etl"]
      interval: 5s
      retries: 5
    ports:
      - 5433:5432
    networks:
      - shared_network
      - default
    volumes:
      - db-staging-volume-md:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  shared_network:
    name: shared_network
    driver: bridge

volumes:
  db-staging-volume-md:
