services:
  clickhouse:
    build:
      context: ../../
      dockerfile: ./docker/clickhouse/Dockerfile
    ports:
      - "9000:9000"
      - "8123:8123"
    env_file:
      - ../../.env.example
    volumes:
      - clickhouse_data:/var/lib/clickhouse
volumes:
  clickhouse_data: