version: '3.8'

services:
  postgres:
    container_name: movies
    build:
      context: ../../
      dockerfile: ./docker/movies/Dockerfile
    environment:
      POSTGRES_DB: movies_database
      POSTGRES_USER: app
      POSTGRES_PASSWORD: qwe123
    hostname: movies
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "etl"]
      interval: 5s
      retries: 5
    ports:
      - 5432:5432
    networks:
      - shared_network
      - default
    volumes:
      - db-movies-volume-md:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  shared_network:
    name: shared_network
    driver: bridge

volumes:
  db-movies-volume-md:
